### ISSUE TITLE
Custom routing

### ISSUE THREAD

**Issue by ferreirix** [jptoto/log4net.ElasticSearch#101]
Hi,

I'm trying to implement routing as described [here](https://www.elastic.co/blog/customizing-your-document-routing) but I haven't figured it out how to specify my route in the connection string.

`    <connectionString value="Server=192.168.xxx.xxx;Index=sync?routing=synx5;" />
`

Thank you in advance for any help :)

**Comment by ferreirix** [comment]
After digging the code a little bit, I believe that we would need to actually add a parameter to support this scenario, right?

In their examples there is: 
`$ curl -XPOST 'http://localhost:9200/store/order?routing=user123' -d '
{
   "productName":"sample",
   "customerID":"user123"
}`

which represents:
`$ curl -XPOST 'http://localhost:9200/{INDEX}/{DOC_TYPE}?routing={ROUTE_PARAM}`

Sorry for some mistake, I'm new to elasticsearch..

Thank you again.

**Comment by ferreirix** [comment]
PR -> #102 

I'd also like to add the possibility to create index per month/year. Right now there is only the option for daily index right? What do you think?

Cheers

**Comment by jptoto** [comment]
@ferreirix Right on! I never thought to add routing but there's certainly no reason why not. Nice work.

I only recently have encountered users who use weekly or monthly indices so that's definitely something that we can implement Mind working on a PR for that?

**Comment by ferreirix** [comment]
Yes i can take a look. Do you have any idea for the xml configuration of this feature?

**Comment by ferreirix** [comment]
@jptoto What do you think of adding a pattern like Index=myIndex{yyyy-mm} . Or do you have another idea? Because this would be a little redundant with the Rolling parameter.
