### ISSUE TITLE
Nuget package is in DEBUG

### ISSUE THREAD

**Issue by mynkow** [jptoto/log4net.ElasticSearch#104]
Could you please release a nuget package built in release?

The current package is in DEBUG:
https://gyazo.com/aa2c7184534152ef02762d0543ad3146

10x

**Comment by jptoto** [comment]
Didn't realize that. Yes, I can. Sorry for not noticing this sooner.

**Comment by jptoto** [comment]
I pushed a 2.4.0 beta version of the library tonight that should be compiled to Release now. Sorry about that.
