### ISSUE TITLE
Failed to send all queued events in OnClose

### ISSUE THREAD

**Issue by sparky2708** [jptoto/log4net.ElasticSearch#107]
I have an ELK/Kibana installation and when I try to use the ElasticSearchAppender I get:

log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ELKAppender]: Failed to send all queued events in OnClose.

What am I doing wrong?

**Comment by jptoto** [comment]
I would need some more info here. Could you generate a log to see what is happening? https://github.com/jptoto/log4net.ElasticSearch/wiki/04-Debugging-log4net.ElasticSearch
