### ISSUE TITLE
Rolling appender does not create new index when under constant load

### ISSUE THREAD

**Issue by cime** [jptoto/log4net.ElasticSearch#31]
I have rolling=true in my connection string, and everything works ok for the first day (when started).
The next day when it should create new index it does not. It's still writing into old index file (today we are 2014/12/23 but it writes into 2014/12/22).
I suspect that it doesn't create new index file because the application I'm logging from is non stop under load and writing into log.

**Comment by jc74** [comment]
See pull request #35
