### ISSUE TITLE
When I send messages to the Appender that has first been sent with a remotingAppender

### ISSUE THREAD

**Issue by turdus** [jptoto/log4net.ElasticSearch#33]
I get no Exception logged :(
When I debugged the code I found that the ExceptionObject is empty (but GetExceptionString) is not.

The documentation for ExceptionObject says: 
"Gets the exception object used to initialize this event. Note that this event may not have a valid exception object. If the event is serialized the exception object will not be transferred. To get the text of the exception the GetExceptionString method must be used not this property."
http://logging.apache.org/log4net/release/sdk/log4net.Core.LoggingEvent.ExceptionObject.html

Is it possible to add a fallback so it gets the Exception from GetExceptionString if no ExcpetionObject is avaible?

Or do I do somwthing wrong when I gon't get a ExceptionObject?

**Comment by jc74** [comment]
Hi @turdus 

What does GetExceptionString return?

**Comment by turdus** [comment]
Hi @jc74!

GetExceptionString returns "ToString()" of the Exception.
First the message then the stacktrace in a string.

**Comment by jc74** [comment]
Ah sorry, I completely misread the issue. I'd assumed there was an error in the appender (log4net reports it's own errors internally). Doh

I'll write a test and pass it by you (if that's ok with @jptoto)

**Comment by turdus** [comment]
To clarify.

I call 
Log.Error("Error", ex);

And I have a remotingAppender as the only appender.

Then I have a service hosting the remotingAppender and there I have a elasticsearchAppender
And I get no Exception logged in elasticsearch.

If I call 
Log.Error("Error",ex);
and have the exact same elastchsearchAppender directly in the config I get the exception logged.

Don't know if I do anything wrong with the remotingAppender or if it is like it is supposed to work.

I have tried a FileAppender and it prints the Exception in both cases.

**Comment by jptoto** [comment]
@turdus I haven't tested against this setup before but I'll get a configuration together and see if I can replicate the issue on my end.
