### ISSUE TITLE
Elastic search throws mapping exception for messageObject property 

### ISSUE THREAD

**Issue by TheSpy** [jptoto/log4net.ElasticSearch#37]
On logEvent request to elastic search messageObject is either string or object. Having that, elastic search throws mapping exception:

MapperParsingException[object mapping for [logEvent] tried to parse as object, but got EOF, has a concrete value been provided to it? status 400

I suppose messageObject should always be a specific object or should always be a string, otherwise elasticsearch is confused how to store it

![image](https://cloud.githubusercontent.com/assets/514031/5875460/04cb1a30-a316-11e4-97ef-8cb97145b667.png)

![image](https://cloud.githubusercontent.com/assets/514031/5875483/38eaa8d0-a316-11e4-8406-d2f10119802f.png)

**Comment by jptoto** [comment]
@TheSpy Interesting. This happens because we're letting ES auto-map the fields. I think I'm going to encourage users to setup index templates http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html before actually starting their logging. This will enforce the field types, such as "object" for messageObject.

**Comment by TheSpy** [comment]
yes, i used a script log-index-spec to create an index and I can see that messageObjec is of type object

![image](https://cloud.githubusercontent.com/assets/514031/5876361/48642ec2-a31f-11e4-8a8b-0c439c1664ea.png)

**Comment by jptoto** [comment]
Ah, but it's being sent as a string. I'll have to put a check in for that.

**Comment by TheSpy** [comment]
I think the solution could be to check if the messageObject is of type of string, and if so the messageObject should just be passed as null as it will be the same as message property anyways. What do you think?

messageObject = loggingEvent.MessageObject != null && loggingEvent.MessageObject.GetType() != typeof(string) ? loggingEvent.MessageObject : new object(),
