### ISSUE TITLE
Log4net throws circular reference exception

### ISSUE THREAD

**Issue by TheSpy** [jptoto/log4net.ElasticSearch#39]
While trying to log an exception in log4net using debug mode 

 try
{
   var z = decimal.Divide(10, 0);
}
catch (Exception ex)
{
   Log.Error(ex);
}

throws circular reference exception

![image](https://cloud.githubusercontent.com/assets/514031/5919649/7466041a-a63e-11e4-886b-0e95e7cb2f9b.png)

at ExtensionMethods.ToJson

![image](https://cloud.githubusercontent.com/assets/514031/5919656/8bf70e26-a63e-11e4-9c90-ccad6e5ffc59.png)

**Comment by TheSpy** [comment]
basically this could be at least a temporary solution

 public static string ToJson<T>(this T self)
        {
            return JsonConvert.SerializeObject(self, Formatting.Indented,
            new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

**Comment by jptoto** [comment]
That's... interesting. Will take a look. Thx!

**Comment by jptoto** [comment]
@TheSpy the problem with that solution is that I'm not using json.net so I can't pass in jsonserializersettings. I was able to duplicate this issue but I'm going to have to figure out a proper fix for it.
