### ISSUE TITLE
If bufferSize not set, logging does not work

### ISSUE THREAD

**Issue by TheSpy** [jptoto/log4net.ElasticSearch#41]
If log4net setting <bufferSize value="val" /> not set, then messages are not logged to elastic search, so the config is not backwards compatible with the earlier version.
Maybe it would make sense to set bufferSize = 1 by default ?

**Comment by jptoto** [comment]
Nice catch. Will fix this in a jiffy and update Nuget.

**Comment by jptoto** [comment]
Traced this back to the config. By default, the BufferSize is set to 512 and I verified that in some debug traces. However, if Lossy is true it really needs an evaluator block or log4net can throw an error. I'm updating the tests and examples to explain this.
```
<evaluator type="log4net.Core.LevelEvaluator">
        <threshold value="ERROR" />
</evaluator>
```
