### ISSUE TITLE
Post multiple events to elasticsearch batch endpoint

### ISSUE THREAD

**Issue by TheSpy** [jptoto/log4net.ElasticSearch#44]
I guess it would make sense to post multiple events to elasticsearch batch endpoint in repository 
https://github.com/jptoto/log4net.ElasticSearch/blob/master/src/log4net.ElasticSearch/Repository.cs#L25
instead of making requests for each logevent
http://www.elastic.co/guide/en/elasticsearch/reference/current/_batch_processing.html

or is there a reason not to do so?

**Comment by jptoto** [comment]
@TheSpy No, you're right. I think that's the next step in the evolution of the appender. Great idea. I'll have to get in and fiddle with the buffer to make sure it works with lossy and non lossy configurations but I definitely think it's a good idea. Should have some time coming up to do it.

**Comment by jptoto** [comment]
This will be done in #48
