### ISSUE TITLE
Elasticsearch Centos 7 box

### ISSUE THREAD

**Issue by RobertReckon** [jptoto/log4net.ElasticSearch#47]
Log4net Appender works on localhost but when I try and use across the network on to Centos 7 Elasticsearch server nothing. And can't see way, its making me sad.

**Comment by jptoto** [comment]
Well we definitely don't want sad users.

Can you try adding the following to your app.config (or web.config) and checking to see what the debug output is? There should be a clue in there.

```<configuration>
   <appSettings>
      <add key="log4net.Internal.Debug" value="true"/>
   </appSettings>

<system.diagnostics>
    <trace autoflush="true">
        <listeners>
            <add 
                name="textWriterTraceListener" 
                type="System.Diagnostics.TextWriterTraceListener" 
                initializeData="C:\temp\log4net.txt" />
        </listeners>
    </trace>
</system.diagnostics>
</configuration>
```
