### ISSUE TITLE
Any plan to support elastic search _bulk operations?

### ISSUE THREAD

**Issue by sjdirect** [jptoto/log4net.ElasticSearch#48]
I've been playing with the buffer and when it flushed it makes individual calls to elasticsearch. Do you have any plan on adding ability to use the Elasticsearch Bulk Api to package many messages into a sing "/_bulk" command?

**Comment by sjdirect** [comment]
Looks like this project has an implementation that may be a good starting point...

https://github.com/urielha/log4stash/blob/master/src/log4net.ElasticSearch/ElasticSearchAppender.cs

**Comment by jptoto** [comment]
@sjdirect I _do_ have plans to support that, yes. Just haven't quite gotten around to it yet. Will definitely get into it shortly.

**Comment by sjdirect** [comment]
Thanks for the reply. Can we leave this issue open until you get around to implementing it? Thanks for building this project! I know it takes a lot of time an effort.

**Comment by jptoto** [comment]
Finished this up and will cut a new release (2.3) shortly.
