### ISSUE TITLE
log data retention

### ISSUE THREAD

**Issue by floekke** [jptoto/log4net.ElasticSearch#49]
Hi
Great little library. How would you recommend handling log data retention?

**Comment by jptoto** [comment]
@floekke Thanks!

I typically use daily indices [(rolling=true in the appender config)](https://github.com/jptoto/log4net.ElasticSearch/blob/master/scripts/App.config.sample). That way a new log is created each day and if you like, you can create an [alias](https://www.elastic.co/guide/en/elasticsearch/reference/1.x/indices-aliases.html) that will give access to all the indices by sitting in front of that. You can use [Curator](https://github.com/elastic/curator) to delete old indices depending on age. We save logs for 30 days at my company. Make sense?

**Comment by floekke** [comment]
Absolutely. Thank you for the information.
