### ISSUE TITLE
Dynamic index name on app.conf

### ISSUE THREAD

**Issue by issam-chouchane** [jptoto/log4net.ElasticSearch#50]
is it possible to have a dynamic index name in the app.conf, some thing like : 
```
<connectionString value="Server=localhost;Index={indexName};Port=9200;rolling=true"/>.
```
The idea is to use the same configuration for differents classes.

Thnx.

**Comment by jptoto** [comment]
@issam-chouchane it's not real easy to do that in the config file and to support it in the log4net.Elasticsearch appender but you can dynamically alter or add appenders in code and on the fly like this example.

http://stackoverflow.com/questions/16336917/can-you-configure-log4net-in-code-instead-of-using-a-config-file

**Comment by issam-chouchane** [comment]
thnx
