### ISSUE TITLE
Sign assembly log4net.ElasticSearch

### ISSUE THREAD

**Issue by maximpashuk** [jptoto/log4net.ElasticSearch#51]
log4net.ElasticSearch, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null 

After signing PublicKeyToken should not be null.

All popular libraries are signed: Newtonsoft.json, NEST, etc.

**Comment by jptoto** [comment]
Can you tell me more about your use case? I'm not really inclined to make a signed version. This is the first request I've had for it. It causes a lot of other issues.
