### ISSUE TITLE
Doesn't work with Shield when SSL is not Enabled

### ISSUE THREAD

**Issue by gmoskovicz** [jptoto/log4net.ElasticSearch#52]
@jptoto 

This library doesn't work with Shield using http with credentials.

We get a unauthorized exception because the HttpWebRequest doesn't contain the authorization header with the user information. In `log4net.ElasticSearch.HttpClient`:

```
            if (uri.Scheme == "https" && !string.IsNullOrWhiteSpace(uri.UserInfo))
            {
                httpWebRequest.Headers.Remove(HttpRequestHeader.Authorization);
                httpWebRequest.Headers.Add(HttpRequestHeader.Authorization, "Basic " + Convert.ToBase64String(Encoding.ASCII.GetBytes(uri.UserInfo)));
            }
```

If Shield is enabled in Elasticsearch, and we are sending the User Information, we should set the authorization headers anyway. We should remove `uri.Scheme == "https"` from the condition. No matter which protocol we are using, if the user is providing credentials, then we should add this to the authorization header.

If the Authorization is provided, and there is no Authentication in Elasticsearch side, then the user information will be avoided.

The code should look like:

```
            if (!string.IsNullOrWhiteSpace(uri.UserInfo))
            {
                httpWebRequest.Headers.Remove(HttpRequestHeader.Authorization);
                httpWebRequest.Headers.Add(HttpRequestHeader.Authorization, "Basic " + Convert.ToBase64String(Encoding.ASCII.GetBytes(uri.UserInfo)));
            }
```

Thanks!

**Comment by gmoskovicz** [comment]
Steps to reproduce:

1. Install Elasticsearch
2. Install Shield plugin
3. Create a user using `esusers useradd user -p password`
4. Add connection string with username and password `<connectionString value="Scheme=http;User=user;Pwd=password;Server=<server-name>;Index=log;Port=9200;rolling=true"/>`

Note that SSL is not enabled, hence `http` scheme is configured.

**Comment by gmoskovicz** [comment]
In NEST, we add the Authentication Headers regardless of http or https:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Connection/HttpConnection.cs#L185

**Comment by jptoto** [comment]
@gmoskovicz Thanks for the link and the reproducible steps! I agree, it's probably a good idea to add the auth headers regardless. I'll get this baked in ASAP.
