### ISSUE TITLE
Bulk API not working with Logsene

### ISSUE THREAD

**Issue by AaronLangley** [jptoto/log4net.ElasticSearch#55]
I'm sending logs to Logsene (https://sematext.com/logsene/) I don't know much about ElasticSearch which is why I'm using a provider like this.

Logsene creates a UUID index for each customer which I've substituted here for "123456789".

I've managed to get it to work where bufferSize = 1, but when greater it gets an exception.

The console log with log4net debugging enabled shows:

System.Net.WebException: Failed to post {"create" : {} }
... to https://logsene-receiver.sematext.com/123456789/syslog/_bulk.

Note - I created a fork where logEvent type can be overridden in the connection string. As I had thought it was failing to recognise the "/_bulk" .  But it was working before and sending with "/123456789/syslog/logEvent/"  and bulk was still failing with: 
https://logsene-receiver.sematext.com/123456789/syslog/logEvent/_bulk.

Any suggestions?

**Comment by jptoto** [comment]
@AaronLangley 

I see from the Logsene docs they _do_ [support the _bulk API](https://sematext.atlassian.net/wiki/display/PUBLOGSENE/Index+Events+via+Elasticsearch+API) but the example they show uses "index" instead of "create" which is what I coded log4net.ElasticSearch to do. Technically both are ok according to the ES docs but Logsene may only support "index".

Since you've got your own fork, try changing the line in https://github.com/jptoto/log4net.ElasticSearch/blob/master/src/log4net.ElasticSearch/Infrastructure/HttpClient.cs that creates the bulk request. It should be line 60. Change the word "create" to "index", recompile your fork, and see if that works.

Let me  know if that works. I may just make that change in `master` if it's more semantically accurate.

**Comment by jptoto** [comment]
@AaronLangley 

Technically both `create` and `index` should work in this case in the _bulk API call. However, if Logsene didn't fully implement the Elasticsearch API, `create` may not work.

I did some research and really, I should be using `index

**Comment by otisg** [comment]
Otis from Sematext Logsene here.  Thanks for the quick turn-around on this!

**Comment by jptoto** [comment]
@otisg No problem!

**Comment by AaronLangley** [comment]
Yes thanks for the quick response.
However it's still not working for me, the error has changed to: Failed to post {"index" : {} }

@otisg is there any other restrictions on the Logsene instance of ElasticSearch? https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html - says it should be able to determine the index and type from the url.

**Comment by jptoto** [comment]
Hmmm. I suppose some more information from the error would be helpful here. I didn't test the change against Logsene but I know the _bulk API call works against Elasticsearch. Is there a way to get more information about the error?

**Comment by AaronLangley** [comment]
Hey jptoto, here's the error details:

```
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
System.Net.WebException: Failed to post {"index" : {} }
{"timeStamp":"2016-01-14T03:34:09.3776700Z","message":"Log test bulk #0","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"19","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:19)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-14T03:34:09.3776700Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
 to https://logsene-receiver.sematext.com/1234567890/syslog/logEvent/_bulk.
  at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T] (System.Uri uri, log4net.ElasticSearch.Infrastructure.T items) [0x000d8] in <filename unknown>:0 
  at log4net.ElasticSearch.Repository.Add (IEnumerable`1 logEvents, Int32 bufferSize) [0x0003b] in <filename unknown>:0 
  at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback (System.Object state) [0x00014] in <filename unknown>:0 
```

And the appender config is

```
    <appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch">
        <layout type="log4net.Layout.PatternLayout,log4net">
			<param name="ConversionPattern" value="%d{ABSOLUTE} %-5p %message" />
        </layout>
        <connectionString value="Scheme=https;Server=logsene-receiver.sematext.com;Index=1234567890/syslog;Port:443;rolling=false;"/>
        <lossy value="false" />
        <evaluator type="log4net.Core.LevelEvaluator">
                <threshold value="ALL" />
        </evaluator>
        <bufferSize value="2" />
    </appender>
```

Note that when I change bufferSize to 1 it is working.

And code is:

```
public static void Main(string[] args)
{
   log4net.Config.XmlConfigurator.Configure(new FileInfo("../../log4net.config"));
   var logger = LogManager.GetLogger(typeof(MainClass));
   Console.WriteLine("Hello World!");
   for (int i = 0; i < 2; i++) {
       logger.InfoFormat("Log test bulk #{0}", i);
   }
}
```

**Comment by gr0** [comment]
Looking at the exception, it seems that there are two issues :) 
First is that the data is sent to the following URL: https://logsene-receiver.sematext.com/1234567890/syslog/logEvent/_bulk
For In Elasticsearch API this means that:
* 1234567890 - is the index name which should be equal to Logsene token (and I assume it is)
* syslog - is the documents type
* logEvent - this would be the identifier, but that is not supported for bulks
* _bulk - the end-point

Such call is not a proper Elasticsearch request, it should be either:
https://logsene-receiver.sematext.com/1234567890/syslog/_bulk
https://logsene-receiver.sematext.com/1234567890/_bulk
https://logsene-receiver.sematext.com/_bulk

Looking at Elasticsearch Bulk API docs (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) we have: "The endpoints are /_bulk, /{index}/_bulk, and {index}/{type}/_bulk". But anyway this is only part of the problem.

There is also one other potential issue I see, but this is on Logsene side - the empty meta line that doesn't contain index and type of the event:
```
Failed to post 
{"index" : {} }
{"timeStamp":"2016-01-14T03:34:09.3776700Z","message":"Log test bulk #0","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"19","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:19)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-14T03:34:09.3776700Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
```
Though we didn't plan to support empty meta lines I'll make that working on our side, to be closer to Elasticsearch API.

**Comment by gr0** [comment]
Just wanted to update on the issue - Logsene is now capable of accepting bulks that doesn't have index and type information in the index meta lines, but have that information in the request. 

Please try indexing again and let us know :)

**Comment by jptoto** [comment]
@gr0 Thanks for the update!

The "out-of-the-box" functionality for log4net.ElasticSearch is to send to 
`/{index}/{type}/_bulk` which is one of the variations you mentioned.

I chose this path and the empty meta line because it suited the log4net.ElasticSearch code structure. It's valid but I'll check into offering alternative methods as options.

@AaronLangley does your fork change that in any way? It may have been causing a pathing issue at Logsene. Is it working ok on your side now?

@gr0 Thanks for the fast turnaround on support at Logsene!

**Comment by gr0** [comment]
No problem, please tell if you run into any more issues.

**Comment by AaronLangley** [comment]
Thanks @jptoto and @gr0 , this is a great help to an ElasticSearch novice!

My impression is Logsene is expecting a "syslog" type, perhaps because that's how I initially used it with the RemoteSyslogAppender. And it's more common anyway for use with other log shippers.  In my fork locally I've made the fixed type "LogEvent" part of the Uri changeable in the ConnectionString so I'll try that this morning. I reckon this together with the upgrade to allow an empty meta line at Logsene will have it working nicely. Will try it out soon!

**Comment by AaronLangley** [comment]
Hi @gr0 

It's mostly working now but 2 out of 20 or so keep failing.

When I run this:

```
public static void Main(string[] args)
{
   log4net.Config.XmlConfigurator.Configure(new FileInfo("../../log4net.config"));
   var logger = LogManager.GetLogger(typeof(MainClass));
   Console.WriteLine("Hello World!");
   for (int i = 0; i < 20; i++) {
       logger.InfoFormat("Log test bulk #{0}", i);
   }
}
```

And bufferSize is set to 5, I'm getting ```Failed to post {"index" : {} }``` but only for message #4 and #8 in this instance. The particular numbers varies but it's similar and happens everytime. Does timeStamp have to be unique with ElasticSearch? When I check Logsene all but these 2 were sent up.

```
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
System.Net.WebException: Failed to post {"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
 to https://logsene-receiver.sematext.com/1234567890/syslog/_bulk.
  at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T] (System.Uri uri, log4net.ElasticSearch.Infrastructure.T items) [0x000cf] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/Infrastructure/HttpClient.cs:78 
  at log4net.ElasticSearch.Repository.Add (IEnumerable`1 logEvents, Int32 bufferSize) [0x00034] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/Repository.cs:40 
  at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback (System.Object state) [0x00014] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/ElasticSearchAppender.cs:93 
System.Net.WebException: Failed to post {"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8990510Z","message":"Log test bulk 710 #8","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8990510Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
 to https://logsene-receiver.sematext.com/1234567890/syslog/_bulk.
  at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T] (System.Uri uri, log4net.ElasticSearch.Infrastructure.T items) [0x000cf] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/Infrastructure/HttpClient.cs:78 
  at log4net.ElasticSearch.Repository.Add (IEnumerable`1 logEvents, Int32 bufferSize) [0x00034] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/Repository.cs:40 
  at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback (System.Object state) [0x00014] in /Users/aaron/Documents/Code/Forks/log4net.ElasticSearch/src/log4net.ElasticSearch/ElasticSearchAppender.cs:93 
log4net: Shutdown called on Hierarchy [log4net-default-repository]
```

**Comment by gr0** [comment]
I have doubts if that is a timestamp issue, because Logsene uses field called _@timestamp_ for date and for sorting your events, not _timeStamp_. Anyway, this is not the cause and I have to dig into the issue, will let you know what I'll find.

**Comment by gr0** [comment]
I debugged a little and tried a different types of bulks, one of the examples I run is the following:

```
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
{"index" : {} }
{"timeStamp":"2016-01-15T08:10:07.8941600Z","message":"Log test bulk 710 #4","messageObject":{},"exception":{},"loggerName":"TestES.MainClass","domain":"TestES.exe","identity":"","level":"INFO","className":"TestES.MainClass","fileName":"/Users/aaron/Projects/TestES/Program.cs","lineNumber":"18","fullInfo":"TestES.MainClass.Main(/Users/aaron/Projects/TestES/Program.cs:18)","methodName":"Main","fix":"LocationInfo, UserName, Identity, Partial","properties":{"log4net:HostName":"Aarons-Mac-mini.local","log4net:Identity":"","log4net:UserName":"aaron","@timestamp":"2016-01-15T08:10:07.8941600Z"},"userName":"aaron","threadName":"1","hostName":"Aarons-Mac-mini.local"}
```

Unfortunately, all the events were properly indexed. Is there a way to see what log4net is sending and what is the response you get from logsene-receiver host?

**Comment by jptoto** [comment]
@AaronLangley FYI if your threshold value is set to "ALL" in your appender config

      <evaluator type="log4net.Core.LevelEvaluator">
                <threshold value="ALL" />
        </evaluator>

The buffer will flush for each call. The threshold is a circuit breaker that will flush the appender in case a log with a certain level is hit. For example, if you set it to "ERROR", the buffer will accumulate to whatever value you set for all DEBUG and INFO messages but if it catches and ERROR event, it will flush the log right away since it hits the threshold.

If you set it to ALL, it will send the _bulk request for every single message and you're not gaining any efficiency but using a buffer > 1.

It may also be helpful to see a debug of what your fork is actually sending. I suggest installing [Fiddler](http://www.telerik.com/fiddler) and set the port of your appender to 8888 so Fiddler catches the requests and you can see them. You may be sending request bodies or urls that you're not expecting.

**Comment by gr0** [comment]
Thanks @jptoto. @AaronLangley if you could install Fiddler and paste both the request and response that would be very, very helpful.

**Comment by gr0** [comment]
I'm not sure what the issue is, but I can replicate the same error being thrown when running a simple code. I'll open an issue with exact description of the thing I'm seeing, the code and the configuration used. Hopefully that will help :)

**Comment by jptoto** [comment]
@gr0 Great, thanks.

**Comment by gr0** [comment]
@AaronLangley I guess you should look at #56 and try indexing with the changes coming from it. Hopefully that will fix all issues when pushing your logs to Logsene.

**Comment by AaronLangley** [comment]
@gr0 - Yes it was the 201 issue for me too!  I added the response code and body to the exception in my fork. (I'm using Xamarin Studio on OS X and haven't yet found a good Mac equivalent of Fidler. )

@jptoto - Thanks for the tip, I've changed the threshold to FATAL. 

Thanks for the help

**Comment by gr0** [comment]
Great to hear that :)
