### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MonDeveloper** [jptoto/log4net.ElasticSearch#57]
@jptoto I'm looking for documentation, there some place to find it?.
My first need (I think it's pretty common) is about the configuration part where even a quick & dirty guide for all the possibile parameters could be a great help for any guys like me and it shouldn't be a huge effort for you. (I hope)

**Comment by jptoto** [comment]
Marco you're right on. I released some major updates and had plans to overhaul the docs before going on holiday and I didn't get them done. I hope to have them compete by the end of this coming weekend. Sorry for the radio silence. 

--
JP Toto

**Comment by jptoto** [comment]
@MonDeveloper Almost done, Marco. I've got at least as much as the old docs and I'll add the rest this weekend, more than likely. https://github.com/jptoto/log4net.ElasticSearch/wiki Thanks for the note.
