### ISSUE TITLE
log4net.ElasticSearch Viewer

### ISSUE THREAD

**Issue by mynkow** [jptoto/log4net.ElasticSearch#62]
What do you use to see the log messages?

Are you building custom UI every time for every project?

**Comment by jptoto** [comment]
@mynkow I almost always use [Kibana](https://www.elastic.co/products/kibana). It's free and is built for Elasticsearch. There are a lot of alternatives out there that will provide dashboards and use Elasticsearch as a source. I don't think I've ever built a custom UI just for logs.

**Comment by jptoto** [comment]
@mynkow Grafana http://grafana.org/ is quite a nice option too. I'm going to explore that soon.
