### ISSUE TITLE
Rolling option

### ISSUE THREAD

**Issue by mynkow** [jptoto/log4net.ElasticSearch#63]
Is there an option to specify the number of indecies like you can do with RollingFileAppender?

**Comment by jptoto** [comment]
@mynkow Yes, you can set rolling=true in the connectionString as shown here https://github.com/jptoto/log4net.ElasticSearch/wiki/02-Appender-Settings That will create a new index each day automatically.

**Comment by mynkow** [comment]
I was actually asking about the max number of days which are kept as elastic search index. For example, if I set the maximum number of of the rolling option to `10` it will keep only the last 10 days and everything else will be deleted.

**Comment by jptoto** [comment]
Ah I see. No, neither Elasticsearch no log4net.Elasticsearch maintain the max number of indices. They will continue being created each day. You can use a tool like Curator https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html to maintain the index count and remove any indexes that are a certain age.

**Comment by urielha** [comment]
Also I have heard that there is a ttl option that you can add to each message you index. It worked for me but I don't know how efficient is it

**Comment by jptoto** [comment]
There _is_ a ttl option but it's deprecated. The [guidance from the Elasticsearch team](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html) is to use rolling indices and then delete old ones.

**Comment by mynkow** [comment]
I found this => https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html

```
Prefer index-per-timeframe to TTL

With TTL , expired documents first have to be marked as deleted then later purged from the index when segments are merged. For append-only time-based data such as log events, it is much more efficient to use an index-per-day / week / month instead of TTLs. Old log data can be removed by simply deleting old indices.
```

Didn't have time to research more.

**Comment by jptoto** [comment]
@mynkow That's the same page I linked to in the previous comment :smile: Since their guidance is to use rolling indices and the convention is to remove old indices with a tool such as Curator, I don't think it would make sense to add any kind of index expiration or deletion to the appender itself.

**Comment by mynkow** [comment]
OMG. It is the same. I didn't realize that. Funny. Sorry for bothering you...

**Comment by jptoto** [comment]
@mynkow 😄
