### ISSUE TITLE
Failed to log to logstash

### ISSUE THREAD

**Issue by betimer** [jptoto/log4net.ElasticSearch#79]
Failed to log to remote logstash, erro log is below:

log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to send all queued events in OnClose.
log4net: No appenders could be found for logger [VCC] repository [log4net-default-repository]
log4net: Please initialize the log4net system properly.
log4net:     Current AppDomain context information: 
log4net:        BaseDirectory   : C:\Repo\vcc\AttendAnywhere\wwwroot\
log4net:        FriendlyName    : /LM/W3SVC/5/ROOT-14-131225972062670747
log4net:        DynamicDirectory: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\7ea2a552\eb8ae04c

**Comment by jptoto** [comment]
@betimer log4net.Elasticsearch is only designed to ship logs directly to Elasticsearch so trying to forward through Logstash won't work. If you'd like some sort of Logstash filtering functionality I recommend trying  an [ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) configuration using Elasticsearch 5.x.
