### ISSUE TITLE
log4net.ElasticSearch dont send data when this.Dispatcher.UnhandledException is use

### ISSUE THREAD

**Issue by SiOuz** [jptoto/log4net.ElasticSearch#84]
I use this code in the app.xaml.cs to catch all exception :

`this.Dispatcher.UnhandledException += OnDispatcherUnhandledException;`

` void OnDispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            string errorMessage = string.Format("An unhandled exception occurred: {0}", e.Exception.Message);
            //e.Exception.Data.Add("ClickOnceCode", ApplicationInfo.ClickOnceCode);
            //e.Exception.Data.Add("HDDSerial", ApplicationInfo.HDDSerial);
            //e.Exception.Data.Add("ApplicationName", ApplicationInfo.ApplicationName);
            log.Error($"{errorMessage}", e.Exception);
            MessageBox.Show(errorMessage, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            e.Handled = true;
        }`

But when this call back is fire, no data is sending to elatics (otherwher i have log in the FileAppender).
(the log works fine with a classic try catch in view model)

Bug ? or any idea why ?

**Comment by jptoto** [comment]
@SiOuz I'm afraid I'm not very good with the Windows forms/xaml threading model so I can't see what might be going on here. But I do suggestion using the [debugging feature for log4het](https://github.com/jptoto/log4net.ElasticSearch/wiki/04-Debugging-log4net.ElasticSearch) to see what's happening in the appender. If you log to a file you can see if it's being called and if it's running into an error.
