### ISSUE TITLE
ElasticSearch 5.3 - log4net.ElasticSearch produces an entry in the Logfile elasticsearch_deprecation.log

### ISSUE THREAD

**Issue by beckma** [jptoto/log4net.ElasticSearch#86]
With ElasticSearch 5.3 log4net.ElasticSearch produces this entries in the Logfile **elasticsearch_deprecation.log**

[2017-04-14T17:40:48,615][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

![image](https://cloud.githubusercontent.com/assets/6991499/25049405/f79b4fa4-2141-11e7-8adc-c10f00cde720.png)

This can be fixed easy with one line of code:

This works:

**const string ContentType = "application/json; charset=UTF-8";** 

![image](https://cloud.githubusercontent.com/assets/6991499/25049465/467cf596-2142-11e7-8f9e-ea1bac64ee51.png)

Could you please fix this "Bug".
Thanks.

Best regards
Martin

**Comment by jptoto** [comment]
Good catch! Will check this out ASAP.

**Comment by jptoto** [comment]
Closed via https://github.com/jptoto/log4net.ElasticSearch/commit/971c1a9280145205546b77f2a1d3cff3e65926d0
