### ISSUE TITLE
Is this replacement for log4net?

### ISSUE THREAD

**Issue by Oleg26Dev** [jptoto/log4net.ElasticSearch#88]
or ES appender only?

I use log4net in my WCF service.
Should I replace it with the log4net.ElasticSearch or  just to add the log4net.ElasticSearchto to have possibilitz to publish logs to ES?

**Comment by jptoto** [comment]
@Oleg26Dev it's just an appender for log4net and requires log4net to work. If you install it from Nuget it will install log4net as a dependency if you don't already have it.

**Comment by Oleg26Dev** [comment]
great! thank you!
