### ISSUE TITLE
Referenced Assembly: update to log4net 2.0.8

### ISSUE THREAD

**Issue by beckma** [jptoto/log4net.ElasticSearch#94]
Is it possible to update the referenced log4net-Assembly to log4net, **Version=2.0.8** ?

Current: log4net, Version=1.2.15.0

![image](https://user-images.githubusercontent.com/6991499/32316236-b6060df6-bfaf-11e7-9757-796a5e2dc2f3.png)

![image](https://user-images.githubusercontent.com/6991499/32316270-cda60b5a-bfaf-11e7-9695-f594dbfcd93c.png)

Thanks.

Best regards
Martin

**Comment by jptoto** [comment]
@beckma The last time I tried this it was a problem because log4net changed their strong signed key but I'll take another look. I'd like it to run the latest version of log4net.

**Comment by jptoto** [comment]
This should now be targeting 2.0.8, at least in the 2.4.1-beta version.
