### ISSUE TITLE
Elastic Cloud connection issue

### ISSUE THREAD

**Issue by aadiwarden** [jptoto/log4net.ElasticSearch#99]
Hi there, so I am trying to connect to an elastic cloud but I'm most probably getting the config file connections wrong since according to #76 it is possible to connect to an elastic cloud, is it possible for somebody to give an example of how the appender would look like while connecting to an elastic cloud server?

**Comment by aadiwarden** [comment]
Hi there, so I am trying to connect to an elastic cloud but I'm most probably getting the config file connections wrong since according to #76 it is possible to connect to an elastic cloud, is it possible for somebody to give an example of how the appender would look like while connecting to an elastic cloud server?

**Comment by jamestoto** [comment]
@aadiwarden can you tell me more about your Elastic cloud setup? Is it on AWS or GCP? Maybe I can duplicate your issue and check it out.

**Comment by jptoto** [comment]
@aadiwarden Can you tell me more about your cloud setup? AWS or GCP? Maybe I can duplicate the issue and check it out.

**Comment by dhirajnayak** [comment]
Trying to log to Elasticsearch on AWS, does not work. Following is the config -
<appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch">
      <layout type="log4net.Layout.PatternLayout,log4net">
        <param name="ConversionPattern" value="%date [%thread] %-5level %message (%logger{3})" />
      </layout>
      <connectionString value="Scheme=http;Server=log;Index=log-myapp-test;Port=80;rolling=true" />
      <lossy value="false" />
      <bufferSize value="100" />
    </appender>

**Comment by solstarz** [comment]
Im also trying to log to Azure in my case, but its not working.

Is there a fix for this issue?

**Comment by jptoto** [comment]
@solstarz can you tell me more about your configuration? What are you trying to log to in Azure? A custom Elasticsearch cluster? What ports are exposed?

@dhirajnayak are you trying to log from outside of AWS or inside? Are your security groups setup correctly? What is the error you're seeing?

https://github.com/jptoto/log4net.ElasticSearch/wiki/04-Debugging-log4net.ElasticSearch The more logs we can have here the better.

**Comment by solstarz** [comment]
Hi @jptoto,

My config is a basic url on a LB with the default port 9200 with basic auth enabled.
The Elastic stack is running on Kubernetes.

Were trying to sent dotnet logging to elasticsearch.
I have created the index in elasticsearch where the entries can be logged, but for some unknown reason it fails.

**Comment by jptoto** [comment]
Right so we need to see what the exact error is. For example, if you created the index with the wrong types, the inserts may not work. Can you do some logging per my last link?

**Comment by solstarz** [comment]
@jptoto With what type should i create the index with? I added the code for debugging, but i dont see any errors in it..

**Comment by jptoto** [comment]
@solstarz it would actually be better if you didn't create the index at all and let log4net.Elasticsearch do it. Then Elasticsearch will set the types on its own. If that does not help and without logs I'm afraid I can't say what the problem might be.

**Comment by a08maheshwari** [comment]
I am facing a similar issue, I am using AWS Elastic Search Service with basic authentication, I tried everything from the link(https://github.com/jptoto/log4net.ElasticSearch/wiki/04-Debugging-log4net.ElasticSearch) as well, but it is not working 
Can you please confirm, it will work for AWS Elastic Search Service or not
